name: intl_utils
description: intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 2.8.1
homepage: https://github.com/localizely/intl_utils

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  archive: ^3.0.0
  args: ^2.0.0
  dart_style: ^2.0.0
  http: ^0.13.0
  intl: ^0.18.0
  path: ^1.8.0
  petitparser: ">=4.0.0 <6.0.0"
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.6
  lints: ^2.0.0
  mockito: ^5.0.12
  test: ^1.16.0
