name: intl_utils
description: intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 2.9.1
homepage: https://github.com/localizely/intl_utils

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ">=6.0.0 <8.0.0"
  archive: ">=3.0.0 <5.0.0"
  args: ^2.0.0
  dart_style: ^3.0.0
  http: ">=0.13.0 <2.0.0"
  intl: ">=0.17.0 <0.21.0"
  path: ^1.8.0
  petitparser: ">=4.0.0 <8.0.0"
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.6
  lints: ^4.0.0
  mockito: ^5.4.3
  test: ^1.16.0
