name: intl_utils
description: intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 1.9.0
homepage: https://github.com/localizely/intl_utils

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  args: '>=0.12.1 <2.0.0'
  archive: ^2.0.13
  intl_translation: 0.17.10+1
  http: ^0.12.2
  path: ^1.7.0
  petitparser: ^3.1.0
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
  mockito: ^4.0.0
